name: Generate static org-roam-ui page
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/publish-org-roam-ui@main
        with:
          org-roam-db-filename: roam.db
          deploy-to-pages: true
          site-title: An org-roam tree of Lisp user space
